# Generated by Django 6.0.2 on 2026-02-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applicaton',
            new_name='applicant',
        ),
    ]
